name: advertising_id
description: A Flutter plugin to access advertising ID.
version: 0.9.0
author: Shinobu Okano <okanoshinobu8@gmail.com>
homepage: https://github.com/operando/advertising_id

flutter:
  plugin:
    androidPackage: com.os.operando.advertisingid
    pluginClass: AdvertisingIdPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
